version: '3.8'

services:
  mongo:
    image: mongo
    container_name: grants_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: .
    container_name: grants_backend
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - mongo
    command: sh -c "dockerize -wait tcp://mongo:27017 -timeout 30s npm start"

volumes:
  mongo_data:
