services:
  mongo:
    image: mongo
    container_name: grants_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: grants_backend
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/grants_db?authSource=admin
      - PORT=4000
      - NODE_ENV=production
    depends_on:
      - mongo

volumes:
  mongo_data:
