services:
  mongo:
    image: mongo
    container_name: grants_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: grants_backend
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
